# Generated by Django 4.2 on 2023-04-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quivial', '0003_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Has been published?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Maximum Marks'),
        ),
    ]
