# Generated by Django 4.2 on 2023-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quivial', '0004_alter_question_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='html',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
